// Mocks generated by Mockito 5.4.2 from annotations
// in gannar_books/test/data/repositories/books_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:gannar_books/data/datasources/network/rest_api_client.dart'
    as _i3;
import 'package:gannar_books/data/dto/books_dto.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBooksDto_0 extends _i1.SmartFake implements _i2.BooksDto {
  _FakeBooksDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RestApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestApiClient extends _i1.Mock implements _i3.RestApiClient {
  MockRestApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BooksDto> getNewBooks() => (super.noSuchMethod(
        Invocation.method(
          #getNewBooks,
          [],
        ),
        returnValue: _i4.Future<_i2.BooksDto>.value(_FakeBooksDto_0(
          this,
          Invocation.method(
            #getNewBooks,
            [],
          ),
        )),
      ) as _i4.Future<_i2.BooksDto>);

  @override
  _i4.Future<_i2.BooksDto> searchBooks(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchBooks,
          [query],
          {#page: page},
        ),
        returnValue: _i4.Future<_i2.BooksDto>.value(_FakeBooksDto_0(
          this,
          Invocation.method(
            #searchBooks,
            [query],
            {#page: page},
          ),
        )),
      ) as _i4.Future<_i2.BooksDto>);
}
